### ISSUE TITLE
Today Widget

### ISSUE THREAD

**Issue by ylor** [thomasfinch/GammaThingy#14]
I'm having trouble with Background App Refresh triggering, in addition to an URL scheme as suggested by another user can help alleviate the issue perhaps a slider widget in the Today section of Notification Center can also help quick management. 

I know as the night goes on I like to make the screen warmer and warmer, so a Today widget would also help in that regard. 

Thanks so much for open-sourcing this. My eyeballs and sleep cycle are grateful!

**Comment by luuuke** [comment]
Background refreshing seems indeed to be the wrong API for automatic switching, SpringBoard uses way too much logic to determine how it should go about refreshing. 
A today widget could also be used to check if the auto change should kick in, just opening the NC would trigger it.

**Comment by lazerwalker** [comment]
Yep, I came on here just to suggest the same thing. I haven't looked into the API myself, but could also likely be a 3D touch contextual action on the 6s / 6s Plus.

I'd love to contribute and throw a quick widget together myself, but no promises when I'll have the time.

**Comment by rolyreyes** [comment]
Since I opened this issue @luuuke contributed a URL scheme and @cfilipov added a dynamic 3D touch action for the icon that launches the app, enables/disables the color temperature shift, and returns the device back to springboard. Both are super useful.

Still hoping someone will be kind enough to whip up a slider. I've looked into it, but I am nowhere near possessing the expertise needed to pull it off.

**Comment by cfilipov** [comment]
@rolyreyes For me at least, the 3D touch shortcut solves the problem of quickly toggling Gamma, and really this shouldn't even be necessary. The root problem seems to be that background app refresh isn't working sufficiently (rarely triggers for me, so I end up using the shortcut). If the app could get more consistent background time then gradually making the screen warmer would over time would be easy.

I've been looking into ways to abuse the background app refresh API or any private API that would allow me to do that but haven't had any luck.

Does anyone know how the built-in alarm clock app works? I feel that might provide a hint of how to do this.

**Comment by lazerwalker** [comment]
If there's a way to abuse the background refresh API, I'm not aware of it. Apple uses a whole bunch of heuristics to figure out when to give an app background processing time, and there isn't a (public) reliable way to work around them. There are a few other similar hacks you can do (e.g. have a server that exists purely to send silent push notifications), but they all tend to fall under similar black-box heuristics problems.

It wouldn't surprise me if the built-in alarm clock uses a private API we could hook into, but it also wouldn't surprise me if it somehow gets special privileges via e.g. the OS doing hardcoded checks for a known bundle ID.

**Comment by thomasfinch** [comment]
I've researched this a bit but I haven't found a good way to refresh the app at a set interval without iOS choosing when to open it. This would be simple if jailbroken by running a daemon (like the actual f.lux tweak) but within the confines of the iOS sandbox it's difficult to get that kind of control. Good idea about the clock app though, I'll investigate how iOS wakes it up when an alarm goes off or a timer is done. It could be as simple as an extra app entitlement, but I kind of doubt it.

**Comment by cfilipov** [comment]
I found a very promising method in [SBApplication.h](https://github.com/CPDigitalDarkroom/iOS9-SpringBoard-Headers/blob/master/SBApplication.h) called `- (void)setApplicationNextWakeDate:`. 

Unfortunately, the only way I can figure out to get an instance of the `SBApplication` is using `-[SBApplicationController applicationsWithDisplayIdentifier]`. The problem is, I think `SBApplicationController` is a class in the SpringBoard app itself, not in a framework, so can't be accessed in an app without jailbreak/mobilesubstrate (and of course the whole benefit of this app is that it works w/o jailbreak). 

`SBApplication` *is* in a framework, so I assume [hope] there must be a way to get an instance for the current application. And hopefully that method does what I hope it does =)

**Comment by thomasfinch** [comment]
SBApplication is a class within SpringBoard, so unfortunately there's no way to access it without being jailbroken. The only way into SpringBoard-land that I've seen so far is through the SpringBoardServices private framework, which is already used to wake the screen during background fetches. I've been through it a bit but there may be some useful stuff in there that I missed that could do this for us.

**Comment by cfilipov** [comment]
@thomasfinch I feel like there has to be a way to tell SpringBoard to wake up the app at some point in the future. [Using XPC](https://gist.github.com/cfilipov/406873356f814d59ef67) looked promising but I get an EXC_BAD_ACCESS. I haven't messed with this before so I might be doing something obviously incorrect. 

See: [iPhoneDevWiki](http://iphonedevwiki.net/index.php/SpringBoard.app/MIG_subsystem)

**Comment by cfilipov** [comment]
Another thing that looks promising: `BKSProcessAssertion`'s `"transientWakeup"` reason. I can't find anything on `"transientWakeup"`, but it looks like `BKSProcessAssertion`, in general, "..allows you to give a certain application permissions to stay alive and not be killed by watchdog" ([iPhoneDevWiki](http://iphonedevwiki.net/index.php/BKSProcessAssertion))

**Comment by cfilipov** [comment]
It looks like the XPC approach probably requires special entitlements (probably com.apple.springboard.launchapplications?) and of course that can't be added because the developer provisioning profile won't have those entitlements.

**Comment by ANGOmarcello** [comment]
This sounds helpful for keeping the app running in the background:
http://stackoverflow.com/questions/12004150/how-to-run-background-process-on-the-ios-using-private-apis-to-sync-email-items#12007135

**Comment by luuuke** [comment]
SpringBoard just uses UILocalNotifications for the alarms, I don't think we can use those to automatically toggle. Maybe we can use interactive notifications, however.

Also, a shot in the dark would be to try if a PCPersistentTimer works.

Regarding setApplicationNextWakeDate: In iOS 4 SpringBoardServices had a function called SBSetApplicationNextWakeDate, but it does no longer exist in more recent OS versions. So I guess it's just some sort of legacy.

@cfilipov: Try to add those entitlements to the compiled binary using ldid.

**Comment by cfilipov** [comment]
@luuuke My understanding was that ldid was only an option for jailbroken devices. Can't add arbitrary entitlements in a sandbox.

**Comment by luuuke** [comment]
@cfilipov Ah well, that's what you get for developing only in jailbroken environments. Thanks for the heads-up!

**Comment by cfilipov** [comment]
@luuuke Yeah I got tired of always being behind in iOS versions and jailbreaks are coming further and further apart. Being able to use my dev profile to side load apps basically fulfills 90% of my needs (i never used tweaks or skins or anything). That said, the thing I really miss is bypassing this annoying code signing lock down. I really hope I can find a solution that will get this thing working in the background. 

I'm trying to avoid using the common VoIP and audio tricks (as mentioned by @ANGOmarcello) to get background time because I want to have a minimal impact on battery life. Perhaps if the app is doing nothing else in the background the impact would be minimal, I haven't measured, but surely something like SBSetApplicationNextWakeDate would be the ideal.

Looks like even BKSProcessAssertion's will require entitlements. So frustrating..

**Comment by luuuke** [comment]
I don't mind being a bit behind as long as I can tinker with the OS :P 
Yep, same, but at this point it seems almost inevitable. I'm wondering if the VoIP thing also keeps SpringBoard from sleeping, which would be absolutely detrimental. Let's wait until @ANGOmarcello has some results, maybe it'll work out just fine :) 
Also, I tried using the PCPersistentTimer, as expected it didn't work out.

**Comment by ANGOmarcello** [comment]
Lock does work as normal. :+1:

**Comment by heliomass** [comment]
It's not a true today extension, but if you have Workflow installed this workflow does a reasonable job of quickly toggling the gamma if you add it to Workflow's today extension: https://github.com/heliomass/iOSWorkflows/blob/master/README.md#toggle-gamma
