### ISSUE TITLE
Background Fetch Alternative

### ISSUE THREAD

**Issue by CasperCLD** [thomasfinch/GammaThingy#37]
Recently I saw some discussion here on this problem. Right now we use background refresh to check if the screen temperature must change, however this isn't very reliable, because it requires the screen to be enabled to change the colour. Now the [latest problems with battery of the Facebook app](https://www.macstories.net/linked/the-background-data-and-battery-usage-of-facebooks-ios-app/) set me thinking. What if we let the background fetch determine whether it's time to switch, and as soon it's time to switch we enable 'Audio background' playing. This allows the app to change the screen colour as soon as the device [is unlocked](http://stackoverflow.com/questions/706344/lock-unlock-events-iphone), because it can continuously run in the background. We disable the 'Audio background' thereafter to keep the battery usage to a minimum. I might be wrong on this idea, because I've never played around with the 'Audio background' mode.
What do you think?

**Comment by CasperCLD** [comment]
So it seems this is possible. I'm writing this down for reference: http://stackoverflow.com/questions/28054669/continuously-run-an-ios-app-in-the-background-even-after-sleep-or-reboot
I'm going to look into it this weekend.

**Comment by thomasfinch** [comment]
These solutions aren't really ideal and I would like to avoid them if possible. Staying awake in the background would be nice for the app functionality but could potentially have a big impact on battery life. Likewise background audio could be battery intensive and would have the downside of not allowing the user to play any music or audio from other apps in the meantime. I'm open to using either, but as I told someone before please test any backgrounding changes on your own device for a few days to make sure it doesn't negatively impact battery life before putting in a pull request. I really don't think the current method of using background fetch is bad at all, it has very little battery impact and usually triggers a color switch within half an hour of the set time for me. Obviously this isn't the best it can possibly be but it's pretty good for working within the confines of Apple's sandbox.

**Comment by titans1127** [comment]
Is the way the official f.lux works by transitioning the screen temperature based on location and sunset/sundown times not possible without jailbreaking?  So far I have been just sticking to manually enabling the screen as I choose to keep Background App Refresh disabled and just change the temperature in the morning or evening as needed.  I'm a fan of how it works on the mac so seamlessly.

Great work either way!  Big fan of all the hard work involved by all to make this work.

**Comment by CasperCLD** [comment]
> Staying awake in the background would be nice for the app functionality but could potentially have a big impact on battery life
Suppose it's only activated around sunset/rise for an hour.. I think this wouldn't drain your battery. But I'll test the app, as I do usual with my software, thoroughly before submitting.
> downside of not allowing the user to play any music or audio from other apps in the meantime
Fair point I'll look into it.

**Comment by CasperCLD** [comment]
The audio going mute had to do with my mac trying to play on the same speaker..  😑 So far I'm seeing a increase of battery from 'zero' (no audio in background) impact to 'low' (with audio background enabled). Thus far promising results, but I'll have to make this a bit smarter to safe battery life.
I'll also create a switch which can enable this extra reliable/battery draining auto switching method.

**Comment by ANGOmarcello** [comment]
Where is the advantage of Audio Backgrounding compared to VOIP Backgrounding?

**Comment by zero2029** [comment]
Guys leave the app as is. I don't care about the app being in a background state. You shouldn't either. It will leave to battery drain. Just manually turn the app on and off... It's that easy. It's not inconvenient. Turn it on when you need it and turn it off when you don't. Leave it as is Thomasfinch.

**Comment by thomasfinch** [comment]
It's nice that you don't care, but other people do. If you'd like to be constructive and actually contribute then you can.

**Comment by zero2029** [comment]
Mr. Finch? Are you upset? Because I wasn't.

**Comment by CasperCLD** [comment]
Good question! Audio Backgrounding gives more control on when the task is running, so you can reduce the battery drainage. Moreover Audio Backgrounding allows you to run in the background continuously, which means it could change the temperature right after you unlock your phone. Thus you wouldn’t have to wait for the 15 min cycle of the VOIP task to kick in.

**Comment by ANGOmarcello** [comment]
Im not entirely convinced of this approach, is it possible to still play music as user?
Also how is this more battery friendly as VOIP backgrounding? (VOIP has an impact of "Zero" and Audio is marked as "Low" in Xcode) Also is it really better to run continuous compared to all 15 minutes?

So to put this next to each other:
VOIP is still seen as a battery problem. And Audio as well. I heard in this repo that Facebook used VOIP to steal background time. What I have read though was that Facebook used the Audio Method. I'm not entirely sure now what is true of this so I will try to avoid Facebook in my conclusion.

So comparing how f.lux does things compared with our options I think, that Fetching is entirely not suited for what we want to do. F.lux runs a deamon in the background of your iOS device. We can assume that the deamon of f.lux is not that much of a battery hug. But what does it do?

As far as I know it runs in the background, we don't know if it runs continuously or only partly. But we know it runs. So to achieve the same functionality VOIP and AUDIO are still viable options. 

I guess that the deamon also only checks for the time and if necessary triggers a switch (and also plays a transition animation) location data is only fetched from inside the f.lux application because it's data only needed once. That should mean the deamon does for obvious reasons no battery intensive operation like network tasks or using gps. If we stick to the same approach VOIP or AUDIO should be no bigger Battery problem then f.lux itself.

So with AUDIO we have the ability to check as offten as we want if it is time to switch and with VOIP every 15 minutes (We also could increase this amount of time for VOIP or decrease it up to a minimum of 10 minutes.) The question is do we need it to be switched on the minute? A little analysis of our best and worst case delay:
-AUDIO we have no delay at all
-VOIP we have a delay of 0 in the best case and a smallest possible worst case of 10-15 minutes depending on how we configure it

The deamon is also launched in the background on system start. (Jailbreak tweaks are reboot persistent.) I don't know if AUDIO is able to accomplish this but with VOIP our ApplicationDidFinishLaunching method is called after system start so that our reboot persistence code can be called right after the user has unlocked his device after a reboot.

Please make your own conclusions and share your thoughts.

I use the VOIP method for a few days now and it works like a charm. Anyone who wants to try it on my fork of GammaThingy is a VOIP branch everyone can try out to build his own opinion.

**Comment by ANGOmarcello** [comment]
You can find a working version of the VOIP Backgrounding here:
https://github.com/ANGOmarcello/GammaThingy/tree/VOIPBackgrounding

**Comment by CasperCLD** [comment]
Hi Ango, I was unaware that the application is able to wake the screen. I see no advantages in the approach in Audio backgrounding over your approach of VOIP backgrounding, please create a merge request for it:)
